#!/sbin/busybox sh

# Ketut P. Kumajaya, Apr 2013, Nov 2013, Mar 2014
# based on gokhanmoral's ramfs for SGS3
# Do not remove above credits header!

/sbin/busybox rm -f /sbin/ueventd
/sbin/busybox ln -s ../init /sbin/ueventd

/sbin/busybox rm -f /sbin/aroma
/sbin/busybox rm -f /res/misc/bootmenu.zip
/sbin/busybox rm -f /sbin/bootmenu.sh
/sbin/busybox rm -f /sbin/killer.sh

DEFAULTROM=`/sbin/busybox cat /.secondrom/media/.defaultrom`

# Galaxy Tab 3 T31x block device
# Don't use /dev/block/platform/*/by-name/* symlink!
SYSTEMDEV="/dev/block/mmcblk0p20"
DATADEV="/dev/block/mmcblk0p21"

if /sbin/busybox [ "$DEFAULTROM" == "1" ]; then
  SYSTEMDEV="/.secondrom/media/.secondrom/system.img"
  if /sbin/busybox [ ! -f /.secondrom/media/.secondrom/data/.layout_version ]; then
    /sbin/busybox mkdir -p /.secondrom/media/.secondrom/data
    /sbin/busybox echo -n 2 > /.secondrom/media/.secondrom/data/.layout_version
  fi
else
  if /sbin/busybox [ ! -f /.secondrom/.layout_version ]; then
    /sbin/busybox echo -n 2 > /.secondrom/.layout_version
  fi
fi

/sbin/busybox mount -t ext4 $SYSTEMDEV /system
/sbin/busybox mount -t f2fs -o inline_xattr $SYSTEMDEV /system

/sbin/busybox mkdir -p /.secondrom/media/0

CM110=0
SAMMY42=0
SAMMY44=0

/sbin/busybox [ -f /system/priv-app/Settings.apk ] && CM110=1
/sbin/busybox [ -f /system/priv-app/SecSettings.apk ] && SAMMY44=1
/sbin/busybox [ -f /system/framework/telephony-common.jar ] && SAMMY42=1

if /sbin/busybox [ "$CM110" == 1 ]; then
  /sbin/busybox echo 1 > /proc/sys/kernel/rom_feature_set
  /sbin/busybox mv -f /res/misc/init.cm11.0/* /
  /sbin/busybox mv -f /res/misc/init.cm11.0/sbin/* /sbin/
  /sbin/busybox mv -f /res/misc/init.cm11.0/sbin/boot/* /sbin/boot/
else
  if /sbin/busybox [ "$SAMMY44" == 1 ]; then
    /sbin/busybox echo 0 > /proc/sys/kernel/rom_feature_set
    /sbin/busybox mv -f /res/misc/init.44/* /
    /sbin/busybox mv -f /res/misc/init.42/sbin/* /sbin/
    /sbin/busybox mv -f /res/misc/init.42/sbin/boot/* /sbin/boot/
  else
    /sbin/busybox echo 0 > /proc/sys/kernel/rom_feature_set
    /sbin/busybox mv -f /res/misc/init.42/* /
    /sbin/busybox mv -f /res/misc/init.42/sbin/* /sbin/
    /sbin/busybox mv -f /res/misc/init.42/sbin/boot/* /sbin/boot/
  fi
fi

F2FS=0

if /sbin/busybox [ $(/sbin/busybox blkid $DATADEV | /sbin/busybox grep -c "ext4") -eq 0 ]; then
  F2FS=1
fi

if /sbin/busybox [ "$DEFAULTROM" == "1" ]; then
  /sbin/busybox mv -f /init.smdk4x12.rc.2 /init.smdk4x12.rc
  if /sbin/busybox [ "$F2FS" == "1" ]; then
    /sbin/busybox mv -f /fstab.smdk4x12.f2fs.2 /fstab.smdk4x12
  else
    /sbin/busybox mv -f /fstab.smdk4x12.2 /fstab.smdk4x12
  fi
else
  if /sbin/busybox [ "$F2FS" == "1" ]; then
    /sbin/busybox mv -f /fstab.smdk4x12.f2fs /fstab.smdk4x12
  fi
fi

/sbin/busybox rm -f /init.smdk4x12.rc.2 /fstab.smdk4x12.2 /fstab.smdk4x12.f2fs /fstab.smdk4x12.f2fs.2

/sbin/busybox umount -d -f /system
/sbin/busybox umount -f /.secondrom
/sbin/busybox umount -f /dev/pts

/sbin/busybox chmod 755 /innt
/sbin/busybox chmod 755 /*.sh
/sbin/busybox chmod 644 /*.smdk4x12*
/sbin/busybox chmod 644 /*.rc
/sbin/busybox chmod 644 /*.prop
/sbin/busybox chmod -R 755 /lib
/sbin/busybox chmod 755 /sbin/boot-patch.sh
/sbin/busybox chmod 755 /sbin/ext/db-bindmount.sh
/sbin/busybox chmod 755 /sbin/ext/modules.sh

/sbin/busybox rm -rf /res/misc/init*

/sbin/busybox mv /innt /init
cd /
exec /init
